// Generated by purs bundle 0.13.4
var PS = {};
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.13.4
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function(exports) {
  
  var G =require("ml5"); 

  exports._kmeans = function(data, options, callback) {
              G.kmeans(data, options, callback)
          };
})(PS["Ml5"] = PS["Ml5"] || {});
(function($PS) {
  // Generated by purs version 0.13.4
  "use strict";
  $PS["Ml5"] = $PS["Ml5"] || {};
  var exports = $PS["Ml5"];
  var $foreign = $PS["Ml5"];             
  var kmeans = function (d) {
      return function (options) {
          return function (cb) {
              return function () {
                  return $foreign["_kmeans"](d, options, cb);
              };
          };
      };
  };
  exports["kmeans"] = kmeans;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.4
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Effect_Console = $PS["Effect.Console"];
  var Ml5 = $PS["Ml5"];                
  var options = {
      k: 3,
      maxIter: 4,
      threshold: 0.5
  };
  var dataPoints = [ {
      x: 0,
      y: 0
  }, {
      x: 0,
      y: 1
  }, {
      x: 1,
      y: 0
  }, {
      x: 1,
      y: 1
  } ];
  var main = function __do() {
      var v = Ml5.kmeans(dataPoints)(options)(function (v) {
          return Effect_Console.log("bla")();
      })();
      return Effect_Console.log("\ud83c\udf5d")();
  };
  exports["dataPoints"] = dataPoints;
  exports["options"] = options;
  exports["main"] = main;
})(PS);
PS["Main"].main();